<form action="<?php echo $this->getSendUrl(); ?>" method="post" class="scaffold-form">
    <label for="name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>

    <div class="input-box">
        <input type="text" name="name" id="name" required>
    </div>

    <label for="email"><?php echo $this->__('Email Address') ?></label>

    <div class="input-box">
        <input type="email" name="email" id="email" value="<?php echo $this->getCustomerEmail(); ?>">
    </div>

    <label for="text" class="required"><em>*</em><?php echo $this->__('Text') ?></label>

    <div class="input-box">
        <textarea name="text" id="" cols="30" rows="10" id="text" required></textarea>
    </div>

    <div class="input-box">
        <button type="submit" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>