<?php
$helper = Mage::helper('oggetto_payment/data');
$params = $helper->getParams();
?>
<form name="gatewayform" method="get" action="<?php echo $helper->getGatewayUrl(); ?>">
    <?php foreach ($params as $name => $value): ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>">
    <?php endforeach; ?>
</form>
<script type="text/javascript">
    document.gatewayform.submit();
</script>